### ISSUE TITLE
Run latest ScalaCheck

### ISSUE THREAD

**Issue by ashawley** [scala/community-builds#1226]
Seth,

Would you be able to run the latest ScalaCheck in the build?

I'm wondering if the changes in https://github.com/typelevel/scalacheck/pull/677 cause problems or not.

Looks like ScalaCheck is frozen at a commit going back to May.

Thanks!

**Comment by SethTisue** [comment]
we're using the 1.14.x branch. I don't know if other changes made on master might cause breakage downstream. but we can find out: https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1911/ (queued)

if it turns out there is too much breakage, then in order to evaluate the effect of typelevel/scalacheck#677, you would need to push a branch somewhere that backports the change to 1.14.x

**Comment by ashawley** [comment]
Ok, good to know.  Thanks for kicking off the build.  There hasn't been significant changes since the 1.14.3 last December, but it is enough to be worrying.

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1911/ 
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1913/
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1914/ 

the lagom failure is unrelated (and has since been addressed)

breeze:

```
[breeze] [error] /home/jenkins/workspace/scala-2.13.x-jdk11-integrate-community-build/target-0.9.16/project-builds/breeze-06bbbd2a1258defb380ed1a67f3c54b337614713/math/src/test/scala/breeze/math/MutableModuleTestBase.scala:127:26: value |: is not a member of Boolean
[breeze] [error]       s"$left != $right" |: close(left, right, TOL)
[breeze] [error]                          ^
```

does this mean anything to you?

advxml: https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1914/artifact/logs/advxml-build.log

I reproduced the failures outside dbuild here, if you want to mess with it: https://github.com/SethTisue/advxml/tree/scalacheck-1.15-snapshot

**Comment by ashawley** [comment]
The breeze compiler error could be the Dotty change, i.e. https://github.com/typelevel/scalacheck/pull/498 or https://github.com/typelevel/scalacheck/pull/667, but I'll need to dig further.  The breeze project may just need the Scalafix.

The advxml test error is strange.  I wonder if ScalaCheck introduced a regression in the generators, or that advxml had a fragile test that got exposed by a ScalaCheck change, or a combination of both.

Anyway, neither of these have to do nested properties, so that puts to rest the concern about https://github.com/typelevel/scalacheck/pull/677, IMO.
