### ISSUE TITLE
Add Cats Effect 3 to the community build

### ISSUE THREAD

**Issue by vasilmkd** [scala/community-builds#1467]
I'm going to attempt this soon. Are there any caveats that I should be aware of?

**Comment by SethTisue** [comment]
What's your motivation with wanting to see the CE2->CE3 upgrade happen here?

I would suggest you hold off until https://github.com/scala/community-build/issues/1456 is done, which will probably happen within the next month or so.

And I wonder whether the upcoming change in the nature of the build will affect your motivation for wanting to do this at all. The community build has always served a dual purpose: it primarily is a gigantic regression test for the Scala compiler, but it has long served a secondary purpose of keeping the Scala OSS ecosystem (including sub-ecosystems such as Typelevel's) on the same page, by providing a big monorepo-style CI for the ecosystem. Which purpose did you have in mind, what motivated you to be interested in this...?

Because the upcoming change really focuses on the regression-test-the-compiler goal and greatly diminishes the build-the-ecosystem-as-a-monorepo aspect.

**Comment by vasilmkd** [comment]
For one, both CE2 and CE3 are part of the dotty/Scala 3 community build, so there's the completeness aspect of it. 😃 

But more seriously, CE3 is the project which sees active development, with CE2 only receiving patches for bug reports. It's a much more active codebase.

I think I've also seen you mention somewhere online that you would like to have it in the community build.

Of course, I'm fine with waiting or dropping this issue completely. 😄

**Comment by SethTisue** [comment]
Okay, let's revisit after #1456. The change will actually make it possible to have both CE2 and CE3 in the build, which is good.

**Comment by vasilmkd** [comment]
That's great news.

I really just wanted to add CE3, not remove CE2, but now I learned that the build cannot have them both at the same time.

Thanks for explaining. Sorry for the confusion.

**Comment by vasilmkd** [comment]
For the record, I'm interested in the regression suite aspect of the community build, and CE3 would be a better target for that in the future.

Feel free to close this issue. Thanks again.

**Comment by SethTisue** [comment]
3ec10e8d433d7915bef0520dbd3617b05535d14a adds a note to `proj/cats-effect.conf` explaining the situation.
