### ISSUE TITLE
Add support for notification on build failure

### ISSUE THREAD

**Issue by dwijnand** [scala/community-builds#228]
Such as @milessabin would be notified when shapeless failed to build.

**Comment by SethTisue** [comment]
this would probably need to be hacked into dbuild? hmm, well, not necessarily — the hacky way would be to put something in this repo that parses the output of dbuild and then does something with it.

in general, it would be nice if generated a collection of Jenkins build artifacts, one per project, instead of a single gigantic log you have to search through.

things to ponder...

**Comment by cunei** [comment]
Incidentally, dbuild already supports informing individual developers when their projects fail to build. See: http://typesafehub.github.io/dbuild/0.9.5/notifications.html
For example:
https://github.com/scala/community-builds/blob/04e4ecc78b685b1aba4d066332b699a62d976d0b/community-2.11.x.dbuild#L13
(this was removed with the move to scala-ci, in e944d66ba7e2fb2408f6d000285eff3b89628504)

**Comment by milessabin** [comment]
Do you mean that the support is still there, and just the configuration has been removed? Or that the support was removed altogether?

**Comment by milessabin** [comment]
Bump ...

**Comment by dwijnand** [comment]
From searching and reading dbuild looks to me like support is still there (unless it's been removed in some parts but not others).

So I'm trialing if it works in #278.

It might need SMTP or encryption or other defaults set, but we'll see how it goes.

**Comment by SethTisue** [comment]
note that we'd need a switch to disable this for builds considered experimental, we don't need to spam anybody while we're messing with their project's entry (or a dependency's entry)

**Comment by milessabin** [comment]
FWIW, I'd prefer the build to be too chatty rather than not chatty enough. Would it be possible for notifications related to experimental builds to be labelled as such so that people can filter them to /dev/null if they wish?

**Comment by SethTisue** [comment]
I really don't think I'm ever going to get to this

partly because I think it would likely be too noisy, and there isn't that much use to it without human involvement. project maintainers are unlikely to know what to make of the failures, and often the failures are really my problem and not theirs.

I think the current human-centric (Seth-centric) approach, with @-notification to maintainers on issues and PRs, is good enough.

**Comment by SethTisue** [comment]
in this vein, see also my remarks at 
https://github.com/scala/community-builds/pull/278#issuecomment-248475941
