### ISSUE TITLE
experiment with coursier for faster maven/ivy resolution?

### ISSUE THREAD

**Issue by adriaanm** [scala/community-builds#248]
https://github.com/alexarchambault/coursier

**Comment by SethTisue** [comment]
would require some dbuild hacking, perhaps @cunei could comment on how ambitious a project it might be

**Comment by cunei** [comment]
Ivy is quite deeply integrated into sbt, and dbuild uses sbt for resolution; it also uses Ivy directly, but only when the "ivy" build system is explicitly used. In order to use dbuild with coursier, that infrastructure would have to be integrated into sbt first, which is absolutely a major piece of work since Ivy behavior and structures are woven into many of the sbt internals. It would be a worthwhile effort, but it would also imply rewriting much of the sbt internals and losing compatibility with current sbt build files, so it's something for a possible sbt 2.0, I believe. Replacing Ivy in sbt is something that has been long discussed; actually doing it implies a serious discussion and a strong commitment to providing the necessary developer resources. @eed3si9n may provide better insights on the matter.

**Comment by eed3si9n** [comment]
There are some corner cases, but for the most part I think of dependency management engines to be just a function from `libraryDependencies` to a list of JARs.

Therefore, [caching the resolution](http://www.scala-sbt.org/0.13/docs/Cached-Resolution.html) and/or swapping the implementation out to sbt-maven-resolver or coursier, would be a natural logical step. I believe coursier tries hard to be compatible with the existing Ivy behavior, and I'd encourage anyone to trying it out especially because Dbuild tends to over-download to guarantee correct state.

**Comment by dwijnand** [comment]
A number of the corner cases have been dealt with in recent versions of coursier.

**Comment by SethTisue** [comment]
for a long time we had to fork any project that used coursier and remove it

but I've discovered recently that projects that use coursier 1.0.0-RC10 work just fine in the community build (!). no idea what got fixed along the way. /cc @alexarchambault

**Comment by alexarchambault** [comment]
@SethTisue What kind of issues were you seeing?

https://github.com/coursier/coursier/issues/187 had been a problem on the CI of ensime, throwing file not found exceptions for directories that should have been created, but it should have been fixed (by https://github.com/coursier/coursier/commit/83a08d172cffa85e23fefb9fa6c5fb1c9e59eca5, for reasons that are unclear, but still ;)

https://github.com/scala/community-builds/issues/294 is still unexplained to me, and I haven't heard of it in other contexts…

I could allow to disable sbt-coursier if some environment variable or Java property is set. That way, you wouldn't have to fork projects to disable it, if anything goes wrong.

**Comment by SethTisue** [comment]
@alexarchambault I'm just not very motivated to go back and try and figure out what was going on before, interesting as it might be to know. mainly just glad it's working!

as for the original idea behind this ticket, I don't think the community build is a good place to pioneer replacing Ivy with Coursier. it should happen in sbt first.
