### ISSUE TITLE
regression: fastparse failing because it uses coursier now

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#294]
a recent commit has:

``` diff
+addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-M14")
```

resulting in at e.g. https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/617/console

```
[fastparse] coursier.ResolutionException: Encountered 3 error(s) in dependency resolution:
[fastparse]   org.scala-lang.modules:scala-xml:1.0.5:
[fastparse]     not found:
[fastparse]       /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/fastparse-6914fec92b407d06ed811a252dfd40c92cdd3a78/.dbuild/local-repo/0/org.scala-lang.modules/scala-xml/1.0.5/ivys/ivy.xml
[fastparse]       /home/jenkins/.ivy2/local/org.scala-lang.modules/scala-xml/1.0.5/ivys/ivy.xml
[fastparse]       https://scala-ci.typesafe.com/artifactory/dbuild/org/scala-lang/modules/scala-xml/1.0.5/scala-xml-1.0.5.pom
[fastparse]       https://scala-ci.typesafe.com/artifactory/dbuild-ivy/org.scala-lang.modules/scala-xml/1.0.5/ivys/ivy.xml
[fastparse]       https://scala-ci.typesafe.com/artifactory/dbuild-unchecked/org/scala-lang/modules/scala-xml/1.0.5/scala-xml-1.0.5.pom
[fastparse]       https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/org/scala-lang/modules/scala-xml/1.0.5/scala-xml-1.0.5.pom
[fastparse]       https://scala-ci.typesafe.com/artifactory/scala-release-temp/org/scala-lang/modules/scala-xml/1.0.5/scala-xml-1.0.5.pom
[fastparse]     wrong checksum: /home/jenkins/workspace/scala-2.12.x-integrate-community-build/./target-0.9.5/project-builds/fastparse-6914fec92b407d06ed811a252dfd40c92cdd3a78/.dbuild/local-repo/0/org/scala-lang/modules/scala-xml/1.0.5/scala-xml-1.0.5.pom
```

**Comment by SethTisue** [comment]
fyi @lihaoyi. not sure if I can disable an sbt plugin in dbuild without forking the project (or just freezing at an earlier commit). I'll look into it. or maybe the plugin has a setting that can be used to switch it off without actually removing it from the build.

**Comment by SethTisue** [comment]
I don't see anything in the dbuild doc for this.

@cvogt does there happen to be some setting in the plugin that will disable it?

for now, I'll just fork: https://github.com/scala/community-builds/pull/296

**Comment by dwijnand** [comment]
There doesn't appear to be anything: https://github.com/alexarchambault/coursier/blob/v1.0.0-M14/plugin/src/main/scala-2.10/coursier/CoursierPlugin.scala#L78-L87

Also, you want to be pinging @alexarchambault, perhaps he'll consider adding one.

**Comment by alexarchambault** [comment]
Would the `/home/jenkins/workspace/scala-2.12.x-integrate-community-build/./target-0.9.5/project-builds/fastparse-6914fec92b407d06ed811a252dfd40c92cdd3a78/.dbuild/local-repo/0/org/scala-lang/modules/scala-xml/1.0.5/scala-xml-1.0.5.pom`, and its checksum (I guess sha1), be around somewhere? Could the checksum file be actually wrong?

I though at first that it might be a duplicate of https://github.com/alexarchambault/coursier/issues/356 (which reminded me of this issue), but the error here is `wrong checksum` rather than `checksum format error`, so the checksum parser seems to have found and successfully parsed something.

**Comment by alexarchambault** [comment]
Also, as a workaround, it should be possible to disable checksum verifying altogether, with something like `coursierChecksums := Seq()`.

**Comment by djspiewak** [comment]
Just found this issue.  It appears to be identical to [this one](https://github.com/alexarchambault/coursier/issues/319).

@alexarchambault I'll experiment with disabling checksumming in our (Verizon's) builds to see if that gets us further on our end of this issue.  My guess is that it won't though, since I've seen other issues where jars were actually invalid (i.e. the wrong contents, not binary corruption) when downloaded via coursier, which makes me suspect that the checksum error is merely a symptom of a larger data corruption issue.  I will note as an aside (and I mentioned this on 319) that the issue is a _lot_ more repeatable on slow connections and/or with a lot of load on the machine doing the resolution.

**Comment by kzys** [comment]
For this particular scala-xml case, the checksum looks correct in Maven Central.

```
% curl --silent http://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.11/1.0.5/scala-xml_2.11-1.0.5.pom | shasum
311c98512e5ada91672f35fe4781720e800772d0  -
% curl --silent http://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.11/1.0.5/scala-xml_2.11-1.0.5.pom.sha1
311c98512e5ada91672f35fe4781720e800772d0%
```

Was it different in the Jenkins sever? It might be too late to ask though.

**Comment by SethTisue** [comment]
I noticed recently that a different project I added to the community build recently had the coursier plugin enabled, but there was no build failure. so, I tried fastparse again and whatever the problem was seems not to be reproducible currently: https://github.com/scala/community-builds/pull/458

I don't know what to make of it, but hey.
