### ISSUE TITLE
Add typelevel/cats to build

### ISSUE THREAD

**Issue by adelbertc** [scala/community-builds#363]
May be blocked on https://github.com/scala/community-builds/issues/13 for `cats-laws`

Currently the build is tracking @SethTisue 's fork. Once https://github.com/typelevel/cats/pull/1415 is merged we should be able to point back to typelevel/cats and run it against all of `catsJVM` (instead of just core and macros).

**Comment by SethTisue** [comment]
1415 is now merged and in #367 I brought my fork up to date with that

in order to get rid of the fork, https://github.com/typelevel/cats/issues/1396 would need to be fixed in the cats repo — right now we are working around it in my fork with https://github.com/SethTisue/cats/commit/04c921f5627c283b05d1407859289042e0d43ce0

**Comment by adelbertc** [comment]
@SethTisue Coincidentally I was just working on a PR for you https://github.com/typelevel/cats/pull/1426 :-)

**Comment by adelbertc** [comment]
@SethTisue Present for you:

https://github.com/scala/community-builds/pull/369

(https://github.com/typelevel/cats/pull/1426 is merged)

**Comment by SethTisue** [comment]
#448 removes a roadblock and adds cats-laws

#375 is the new #369

**Comment by adelbertc** [comment]
Fixed by https://github.com/scala/community-builds/pull/375
