### ISSUE TITLE
add scala-debugger

### ISSUE THREAD

**Issue by fommil** [scala/community-builds#463]
@chipsenkbeil

**Comment by chipsenkbeil** [comment]
@fommil, if dependencies need to already be in the build, then part of the debugger could be included, right? Looks like it would just be the debugger API, but it has slf4j-api as a dependency. Is that an issue? The language and tool modules have other dependencies not in the community builds. Ensime only uses the API module, so that should be okay, I'm assuming.

Also, I'd have to exclude the sbt plugin as they say, since it isn't using 2.12.

**Comment by SethTisue** [comment]
Java-based dependencies like slf4j are always fine, dbuild will just pull those binary JARs from (e.g.) Maven Central. it's only Scala-based dependencies that need to be explicitly included in the community build so they can be rebuilt from source. I have edited https://github.com/scala/community-builds/wiki/Eligibility to be clearer on this point.

I agree that it would be very much worthwhile to get even just the `scalaDebuggerApi` subproject included.
