### ISSUE TITLE
regression: Scala.js failing in all of the community builds

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#465]
so e.g. at https://scala-ci.typesafe.com/view/scala-2.11.x/job/scala-2.11.x-integrate-community-build/492/consoleFull we see:

```
[scala-js] [error]           exportsNamespace.org.scalajs.testinterface.internal.detectFrameworks(data);
[scala-js] [error]                               ^
[scala-js] [error] 
[scala-js] [error] TypeError: Cannot read property 'scalajs' of undefined
[scala-js] [error]     at [stdin]:40:31
[scala-js] [error]     at [stdin]:44:9
[scala-js] [error]     at Object.exports.runInThisContext (vm.js:54:17)
[scala-js] [error]     at Object.<anonymous> ([stdin]-wrapper:6:22)
[scala-js] [error]     at Module._compile (module.js:410:26)
[scala-js] [error]     at node.js:578:27
[scala-js] [error]     at nextTickCallbackWith0Args (node.js:419:9)
[scala-js] [error]     at process._tickCallback (node.js:348:13)
[scala-js] org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: Node.js exited with code 1
```

@sjrd any idea what this is about?

**Comment by SethTisue** [comment]
something to do with https://github.com/scala-js/scala-js/pull/2740 ?

**Comment by sjrd** [comment]
Yep, it's definitely about https://github.com/scala-js/scala-js/pull/2740.
The problem is that the community builds insists on `test`ing every project that is a dependency of the project we really care about, i.e. `testSuite/test`. This causes `library/test` to be executed in the community build, although it's never part of our test harness.

The thing is: `library/test` is empty; it doesn't have any test. Most importantly, it doesn't have any testing *framework*, and that means it doesn't depend on our testing interface. The changes in https://github.com/scala-js/scala-js/pull/2740 cause the `test` task to crash if the testing interface is not in scope, whereas before it would silently (and correctly) return an empty list of testing frameworks, and hence execute 0 test.

We can fix this on our end. A PR will arrive soon.

**Comment by sjrd** [comment]
https://github.com/scala-js/scala-js/pull/2753
