### ISSUE TITLE
regression: scalaprops doesn't compile

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#504]
seen at e.g. https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1362/consoleFull

```
[scalaprops] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.7-RC1/project-builds/scalaprops-bc63205fda5487e8cff721bb2a176e24c4c06dc0/gen/src/main/scala/scalaprops/Gen.scala:842: not found: type CorecursiveList
[scalaprops] [error]   implicit def corecursiveListGen[A: Gen]: Gen[CorecursiveList[A]] =
[scalaprops] [error]   implicit def corecursiveListGen[A: Gen]: Gen[CorecursiveList[A]] =
[scalaprops] [error]                                                ^
```

@xuwei-k any idea what this is about? looks related to scalaz upgrade?

I'll try to work around it for now by freezing scalaprops at 275dec775d7a9443f31f18a6258fbfd443e8deb1 (EDIT: frozen in 0c4961020a3b2336a95c64da83dcebbe315927e2)

**Comment by xuwei-k** [comment]
> looks related to scalaz upgrade?

Ah, Yes I was cherry-picked CorecursiveList into the scalaz `series/7.2.x` branch, release scalaz 7.2.10, and use CorecursiveList in scalaprops.

https://github.com/scalaz/scalaz/commits/series/7.2.x

```
00ed5e7 Setting version to 7.2.11-SNAPSHOT
0ca3f86 Setting version to 7.2.10
7b057db Java 9
ee8065a update latest version sbt-extras
1e3ce71 support scala-native
8c7d8ab Change CrossVersion.full to CrossVersion.patch
268decf add autoCloseableResource, resourceFromAutoCloseable
d1f870c use ScalaJSPlugin.autoImport.isScalaJSProject
edf4e5d Add method Leibniz#flip.
5d4fb0b Change default Scala version to 2.12.1.
0b2a4c4 Update comment at ISet#map about Functor requirements.
5fbbe39 CorecursiveList
0506a65 Setting version to 7.2.10-SNAPSHOT
5a8c379 Setting version to 7.2.9
```

freeze https://github.com/scalaz/scalaz/tree/8c7d8ab41f4b40d02f938f9609be0f7e3568764f (before scala-native commit) instead of https://github.com/scalaz/scalaz/tree/0506a651beab3a700f241a8cb451280354b0b7c1 ?

https://github.com/scala/community-builds/issues/500

**Comment by SethTisue** [comment]
thank you Kenji!
