### ISSUE TITLE
add a compiler and/or sbt plugin to every project?

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#553]
the desire for this has come up at least three times:

* to count the number of lines of code in the build (https://github.com/scala/community-builds/issues/59#issuecomment-288240127)
* in the context of wanting to test [HPE Fortify](https://www.lightbend.com/blog/lightbend-and-hpe-announce-new-hpe-fortify-scala-plugin-for-static-application-security-testing-sast)
* @dragos said today they had hoped to do this to test [Hydra](https://triplequote.com)

According to Iulian, if I understood correctly, @cunei said dbuild currently can't do this. Toni, is that correct?

**Comment by cunei** [comment]
I think not. The "commands" in theory could be used to inject additional files, and therefore to add a plugin file, but the "commands" are only invoked after the dependencies have already been rearranged, therefore well after the sbt project had been loaded, and therefore too late for plugins (but still in time to add source files to the project, for instance).
I'm thinking... Well, the options `settings` and `sbt-settings` can be used for multiple levels, and therefore can also be used to append stuff to the meta sbt project (the plugins one). The `addSbtPlugin` thing is really just a convenience shortcut to say `libraryDependencies += sbtPluginExtra(dependency, sbtVersion, scalaVersion)` (see `Defaults.scala` in the sbt source). Therefore I think you should be able to use `settings` or `sbt-settings` to patch `libraryDependencies` for the plugins level, in order to inject new plugins. See: http://typesafehub.github.io/dbuild/0.9.6/plugins.html#the-settings

**Comment by dwijnand** [comment]
Careful not to confuse sbt plugins with compiler plugins.

**Comment by cunei** [comment]
Sorry, I misread

**Comment by dragos** [comment]
Indeed... for us, it's the Sbt plugin that we need to add. I'm guessing @SethTisue was thinking about compiler plugins.

**Comment by cunei** [comment]
The same should apply for compiler plugins as well, actually. The line `addCompilerPlugin` is just `libraryDependencies += compilerPlugin(dependency)`, and `scalacOptions` can be tweaked in the same way by using `settings`.

**Comment by SethTisue** [comment]
I've renamed the issue to cover both kinds :-)

**Comment by dwijnand** [comment]
I tested and `libraryDependencies in ThisBuild += compilerPlugin(dependency)` adds the compiler plugin to all projects in the build.

For sbt plugins I assume what's needed is _enabling_ the plugin in every project. And, yes, I agree, having the ability to do so once at the use site (as opposed to the `triggers` definition site) would make things more straight-forward for lots of builds.

**Comment by SethTisue** [comment]
> I tested and libraryDependencies in ThisBuild += compilerPlugin(dependency) adds the compiler plugin to all projects in the build.

yup, it works, I was successful with this over at https://github.com/scala/community-builds/pull/639

**Comment by SethTisue** [comment]
I don't think we need to leave this ticket open, as the compiler-plugin aspect is solved, and no need has arisen for the sbt plugin aspect.
