### ISSUE TITLE
publish all built artifacts to a generally accessible location

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#611]
so that people who want to test their own projects against a collection of libraries all built against the latest Scala (or Scala PR), can

suggested by @hrhino in sbt/sbt just now, but I know the idea has come up before. I don't _think_ there's already a ticket on it

dbuild already operates by hijacking the `publish` task, so it's quite possible that it's actually already creating a directory that has the right structure, and we'd only need to make it public?

(we'd have to make sure to provide enough disk space...)

**Comment by SethTisue** [comment]
@cunei any thoughts on whether this would need any work on the dbuild side...?

**Comment by dwijnand** [comment]
See https://github.com/sbt/sbt-standalone-build, where (among other goals) we want to publish nightly builds of sbt (from the various repo builds).

**Comment by cunei** [comment]
It's very easy: dbuild already has support for publishing the generated artifacts to the local file system, to Artifactory or to Maven repos, to S3, to arbitrary servers via scp, or to Bintray. All the details are here: http://typesafehub.github.io/dbuild/0.9.9/deploy.html#the-deploy-section

**Comment by SethTisue** [comment]
I've been thinking about this again lately, and I'd like to record one thought that holds me back, which is that even if we did publish the artifacts, the process of using them for testing is one that would be difficult for library authors. we'd need to write instructions that explained how to alter their builds to retrieve artifacts from our custom resolver, and the details of this would be fiddly, and each individual library maintainer would rarely need to do this, so every time it came up they'd be learning it for the first time or re-learning it pretty much from scratch since they'd be unlikely to remember the details from last time. library maintainers are generally already maxed out on this kind of rigmarole, it's hard enough to keep up with all the routine stuff they already need to do, without getting mixed up in this too.

so my sense is that even if we did this, it would basically only be me using it. I'd have to fork the library myself, and update the build definition myself, and then point the library maintainer to the branch and say, "here, I set it all up for you, now you can use this branch from my fork to do your troubleshooting on".

it might still be worth doing, but I don't see a path for this to become easy enough for the vast majority of library maintainers to do themselves.

**Comment by hrhino** [comment]
> so my sense is that even if we did this, it would basically only be me using it.

So at the very least, speaking as a maintainer of few libraries, I'd be interested in using it to test out prerelease Scalas (Scalæ?) on my company's rather large closed-source codebase, which is why this interested me to begin with. Last time I checked, all of our Scala dependencies were to community-build projects (for 2.12). I wonder how many corporate Scala users would be willing to do the same. I tried setting up `dbuild`, but it was more complicated than I could manage in the little free time I had.

If I'm not mistaken, wouldn't the only changes be to add the community-builds resolver, then adjust the `ModuleID`s of all the dependencies to community-build projects to point to whatever the mangled version is? I wonder if that's within the grasp of a sufficiently perspicacious sbt plugin. (It could download the dbuild hocon for the relevant version and use that to sniff out which dependencies needed changed.)

Besides testing with versions of the library build with the absolute-latest scala nightly, the main difficulty for me to testing prerelease Scala versions are compiler plugins (mainly paradise and acyclic; silencer and kind-projector don't publish against minor versions). It's not necessarily bad to use the official versions of libraries published with an older Scala for purposes of testing the compiler on one's own codebase, but setting up CI to build + publish + use a handful of compiler plugins is not simple (even with dbuild).

I follow the scala/bug repo pretty closely, and I notice that whenever a new Scala version comes out, a handful of bugs come in with a description like "my closed-source Scala codebase won't compile with the latest Scala version; please help!", and in that case there's nothing that can be done until 3 or 6 months out when the next minor release is planned. I don't know how many people could be convinced to add this to their CI, but it could be sold as "here, if you use this plugin and report (minimized!) failures you see, we can do a better job of making sure that each new Scala version has no regressions". 

Either way, this is just my opinion here, and since I wouldn't be the one setting up scala-ci to publish these, it's up to how much effort you think it's worth putting in. (My quest to rejoin the world of OSS is coming along pretty well, so I'd be willing to try to get a plugin working (if I don't misunderstand what it would need to do).)

Thanks either way!

**Comment by SethTisue** [comment]
I'll think on it... further context is at https://github.com/scala/scala-dev/issues/648

**Comment by SethTisue** [comment]
I don't think this is ever going to happen, since there's no longer a plan to do Scala 2.14 (with concomitant rebuilding of the ecosystem), and the Scala 3 picture is different (TASTy!)

**Comment by SethTisue** [comment]
This idea came up again recently at #1602. I noted the usual workarounds there, and I'll repeat it here for posterity:

> In order to do this kind of testing on my own laptop, I sometimes locally publish kind-projector and other compiler plugins. It wouldn't be out of the question for a project maintainer's CI setup to do the same thing.

> Another usable workaround is to override the Scala version on the dependency, so you (for example) continue using the 2.13.9 kind-projector even with a 2.13.10 snapshot. At least 95% of the time, there aren't any relevant breaking changes to the compiler and this approach works fine.
