### ISSUE TITLE
2.13: re-enable Scala.js tests

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#674]
as per https://github.com/scala/community-builds/commit/d44382bdad9939acf7c3979436f5be531cb92327

cc @sjrd

**Comment by SethTisue** [comment]
Sébastien, I'll need your guidance here, I don't understand the failures. let us know if we can answer any questions about what's changed in 2.13, and hopefully we'll meet in the middle somewhere.

**Comment by SethTisue** [comment]
I assume it will be reproducible outside of dbuild if you just use the latest 2.13 nightly. if not let me know

**Comment by sjrd** [comment]
Yes, the 2.13 nightly reproduced the bug.

This is an easy one: it's because the fix for https://github.com/scala/bug/issues/10512 hasn't reached your 2.13.x branch yet, but we already have tests for it. The tests are disabled in 2.12.{0-4} and 2.13.0-M2, because those versions are known to be defective wrt. it, but "2.13.0-pre-whatever" does not qualify to exclude the test.

In fact, `testSuiteJVM/test` fails too, for the exact same reason (at run-time instead of link-time, obviously).

So the fix for this one is just that you forward merge 2.12.x into 2.13.x.

**Comment by SethTisue** [comment]
aha. okay, I think at our team meeting yesterday someone said they'd be doing that shortly (in the next few days)

**Comment by sjrd** [comment]
If I manually disable that test, both `testSuiteJVM/test` and `testSuite/test` succeed.

**Comment by SethTisue** [comment]
update: I merged 2.12.x onto 2.13.x, but there isn't a new nightly build yet

**Comment by SethTisue** [comment]
new nightly: 2.13.0-pre-79e5101

trying to re-enable the test suite uncovered a regression in (I think) constant-folding: https://github.com/scala/scala-dev/issues/465

**Comment by SethTisue** [comment]
current status: we're on the new collections now, so scala-js has worse problems now :-)

the current config file has tests re-enabled (so I'm closing this ticket), but the run doesn't even get that far, currently.

scala-js-stubs works, which is the part downstream projects need.
