### ISSUE TITLE
generate one log file per project, not one gigantic unwieldy single log file

### ISSUE THREAD

**Issue by SethTisue** [scala/community-builds#699]
either by changing dbuild, or by post-processing the current gigantic log

the individual files would then be available as build artifacts in the Jenkins web UI

this would

* make my life as maintainer easier, finding stuff in the current gigantic log just sucks
* make it easier for outside contributors to help
* make it easier for the maintainers of included projects to help when something goes wrong with their project since we could give them a URL that just has the log they care about
* be a good step towards https://github.com/scala/community-builds/issues/321

**Comment by SethTisue** [comment]
@cunei this doesn't already exist in dbuild, right? do you think this would be an easy modification to dbuild?

**Comment by retronym** [comment]
What would be really great would be to emit a JUnit XML format file. Treat each project as a "test class". Treat "extract", "compile" "test" as test methods. Stick the log output in the file, and let Jenkins render it. For steps that are blocked by prior failures, mark the status as "skipped".

The report tracks pass/fail history, so you can easily find the first build in which a particular failure occurred. This feature is a little bit less useful when we use parameterized builds to run random builds in the sequence, rather than just running a clean sequence of nightly or mergely builds.

**Comment by retronym** [comment]
In the meantime, what's the best `curl/grep` combo to find errors? I came up with:

```
curl --silent https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk9-integrate-community-build/2/consoleText | grep -E '(:error\]|\ \[error\])' /tmp/community-build.log | grep -iv 'WARNING: ' | grep -v SLF4J
```

**Comment by retronym** [comment]
As a stopgap, I've enabled the [Log Parser Plugin](scala-2.12.x-jdk9-integrate-community-build)

I've updated the configuration, so far just of the [scala-2.12.x-jdk9-integrate-community-build](https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk9-integrate-community-build/) build, with some patterns.

with

```
cat << 'EOF' > ./logparser.conf
ok /warning: Ignoring option/
ok /[Ii]llegal reflective access/
ok /Please consider reporting this to the maintainers/
ok /illegal access operations/
warning /build did not complete./
ok /SLF4J: /
error /\[error\]/
warning /:error\]/
warning /[Ww]arning/
warning / WARNING:/
start /.*--== (Extracting dependencies|Building|Console Notifications)/
EOF
```

It isn't particularly pretty, but maybe it is a net positive. It should show up as a new tab in the results of the [currently rebuilding build 3](https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk9-integrate-community-build/3/). _UPDATE_ Here's the [output](https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk9-integrate-community-build/3/parsed_console/)

 If we want to keep it around, we can share that config with the other community builds (either by putting the config file into each branch of the `communitybuilds` repo, or just on disk on Jenkins)

**Comment by cunei** [comment]
Have you tried looking into `target-0.9.11/logs`...? You will find all the logs there.

**Comment by cunei** [comment]
To elaborate further: the compilations and extractions are logged separately, as well as being piped to the master log, since at least originally they were meant to be produced by separate compilation workers: the 'd' in dbuild was originally for 'distributed'. Later that went the same as the 's' in sbt, but I digress.

The logs are identified by extraction/build UUID, so it is not immediately obvious which refers to which, unless the extraction/build dirs are cleaned beforehand. An alternative is inspecting the overall build corresponding to the repeatable UUID using something like 'drepo' (which is broken in recent releases, btw), in order to get the project UUIDs.  But the log files, technically, are there and already split.

That said, @retronym's approach of using the log parser seems way better for the practical purpose of locating the failures, so I see that as a great solution.

**Comment by retronym** [comment]
I've copied that config to the other two community build jobs.

**Comment by SethTisue** [comment]
Jason's thing is useful (thank you!), but it only runs server-side, and I'm often doing local runs, and it doesn't address all the use cases for this

in particular, I want to be able to direct a project maintainer to a file containing the complete build log for their project only

Toni's suggested approach (thank you!) would be elegant, but it having find the right logfiles seems a bit trickier than I want to tackle

so with a bit of regret at the inelegance, I just wrote some code to split `dbuild.out`. it is clunky but does the job: 6fa0c7ebff8ade69ccb3394613ec3c2f2a9e6f52

**Comment by SethTisue** [comment]
and I went around and added an "archive the artifacts" post-build step to all of the jobs

example results: https://scala-ci.typesafe.com/view/scala-2.11.x/job/scala-2.11.x-integrate-community-build/1276/artifact/

**Comment by ennru** [comment]
Great! Thank you.
