### ISSUE TITLE
Frozen scalacheck

### ISSUE THREAD

**Issue by ashawley** [scala/community-builds#712]
Any reason to have scalacheck frozen still?  Looks like the community build has it frozen to a commit that is a year old.  

There has been a lot of commits recently to scalacheck, and it seems like a 1.14.0 release is going to drop pretty soon. 

Does the community build breathe the compiled scalacheck in to other projects?  Is it a pain in the neck when scalacheck project breaks binary compatibility for downstream projects?

**Comment by SethTisue** [comment]
I froze ScalaCheck in the 2.12 community build because a ScalaCheck change broke the ScalaCheck integration in specs2 3.9.x

in specs2 4.x, there's no problem. the 2.13 community build is on specs2 4.x

pushing the specs2 3.9.x->4.x upgrade through the 2.12 build is probably doable, but I don't consider it a priority.

> Does the community build breathe the compiled scalacheck in to other projects? 

eh? (I have some guesses about what you had in mind before auto-correct kicked in, but better you just re-ask...)

> Is it a pain in the neck when scalacheck project breaks binary compatibility for downstream projects?

not sure how to answer because I'm not sure understand the thinking behind the question. can you expand?

in general, the community build requires source compatibility, the actual ecosystem requires binary compatibility.

**Comment by ashawley** [comment]
> I froze ScalaCheck in the 2.12 community build because a ScalaCheck change broke the ScalaCheck integration in specs2 3.9.x

This answers my question about dbuild breathing scalacheck to downstream projects.  This is what I was getting at.

**Comment by SethTisue** [comment]
> pushing the specs2 3.9.x->4.x upgrade through the 2.12 build is probably doable, but I don't consider it a priority

I got thinking about this, and I think I changed my mind. working on it now at #715

**Comment by SethTisue** [comment]
#715 was merged
