### ISSUE TITLE
Get off custom fork for Java 8 testing

### ISSUE THREAD

**Issue by gkossakowski** [scala/community-builds#83]
The [Community-2.11.x-Java8](https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x-Java8/) jenkins job has been running stripped down version of community build. That version has been created by @retronym in his own fork.

We should figure out all necessary fixes so we can get off the fork and custom branch. Ideally, we should use exactly the same definition for both Java 6 and Java 8. If some custiomizations are needed (e.g. for swing), the difference between branches should be kept minimal.

This issue is here to track progress of that effort. The work has been motivated by the fact that the fork started to get stale and failing for some other reasons.

**Comment by SethTisue** [comment]
closing, because the current iteration of this work is (rather arbitrarily) being tracked in another repo: https://github.com/scala/scala-jenkins-infra/pull/112

the sbt plugin Greg mentions has gone away because we are no longer building sbt plugins from source as part of the community build; since they are Scala 2.10-based anyway, we just pull them as binary dependencies.

as for "Ideally, we should use exactly the same definition for both Java 6 and Java 8", that is not the current plan. the current plan is to more or less freeze the 2.11/JDK6 community build, and try to keep 2.11/JDK8 and 2.12/JDK8 more or less in sync, with fresher versions of everything.
