### ISSUE TITLE
Community build failing in Play's SBT plugin

### ISSUE THREAD

**Issue by retronym** [scala/community-builds#96]
Recent community build failure: https://jenkins-dbuild.typesafe.com:8499/view/Shared/job/Community-2.11.x/513/console

Perhaps due to https://github.com/playframework/playframework/pull/4108:

```
[Play2-SBT-Plugin] [warn] Run 'evicted' to see detailed eviction warnings
[Play2-SBT-Plugin] [info] Compiling 26 Scala sources to /mnt/dbuild/jenkinsdbuild4/localhome-a8/workspace/Community-2.11.x/target-0.9.1/project-builds/Play2-SBT-Plugin-fcfeaa98ab8e414fb0e8db6b74e8dffdb3256dfa/framework/src/sbt-plugin/target/scala-2.10.4-dbuildx02077049a08aeb2751a9a426dc8c29feded3d129/sbt-0.13/classes...
[Play2-SBT-Plugin] [warn] /mnt/dbuild/jenkinsdbuild4/localhome-a8/workspace/Community-2.11.x/target-0.9.1/project-builds/Play2-SBT-Plugin-fcfeaa98ab8e414fb0e8db6b74e8dffdb3256dfa/framework/src/sbt-plugin/src/main/scala/PlayCommands.scala:400: Adapting argument list by creating a 3-tuple: this may not be what you want.
[Play2-SBT-Plugin] [warn]         signature: ArrowAssoc.->[B](y: B): (A, B)
[Play2-SBT-Plugin] [warn]   given arguments: module.\("@organisation").text, module.\("@name").text, rev.\("@name")
[Play2-SBT-Plugin] [warn]  after adaptation: ArrowAssoc.->((module.\("@organisation").text, module.\("@name").text, rev.\("@name")): (String, String, scala.xml.NodeSeq))
[Play2-SBT-Plugin] [warn]             'module -> (module \ "@organisation" text, module \ "@name" text, rev \ "@name"),
[Play2-SBT-Plugin] [warn]                     ^
[Play2-SBT-Plugin] [error] /mnt/dbuild/jenkinsdbuild4/localhome-a8/workspace/Community-2.11.x/target-0.9.1/project-builds/Play2-SBT-Plugin-fcfeaa98ab8e414fb0e8db6b74e8dffdb3256dfa/framework/src/sbt-plugin/src/main/scala/PlayEclipse.scala:40: not found: value setting
[Play2-SBT-Plugin] [error]         setting(crossTarget in ref, state) map { ct =>
[Play2-SBT-Plugin] [error]         ^
[Play2-SBT-Plugin] [error] /mnt/dbuild/jenkinsdbuild4/localhome-a8/workspace/Community-2.11.x/target-0.9.1/project-builds/Play2-SBT-Plugin-fcfeaa98ab8e414fb0e8db6b74e8dffdb3256dfa/framework/src/sbt-plugin/src/main/scala/PlayEclipse.scala:57: not found: value evaluateTask
[Play2-SBT-Plugin] [error]         evaluateTask(dependencyClasspath in Runtime, ref, state) map { classpath =>
[Play2-SBT-Plugin] [error]         ^
[Play2-SBT-Plugin] [error] /mnt/dbuild/jenkinsdbuild4/localhome-a8/workspace/Community-2.11.x/target-0.9.1/project-builds/Play2-SBT-Plugin-fcfeaa98ab8e414fb0e8db6b74e8dffdb3256dfa/framework/src/sbt-plugin/src/main/scala/PlayEclipse.scala:81: not found: value setting
[Play2-SBT-Plugin] [error]         (setting(baseDirectory in ref, state) |@| setting(key in ref, state)) { (base, src) =>
[Play2-SBT-Plugin] [error]          ^
[Play2-SBT-Plugin] [warn] one warning found
[Play2-SBT-Plugin] [error] three errors found
[Play2-SBT-Plugin] [error] (SBT-Plugin/compile:compile) Compilation failed
```

/cc @jroper

**Comment by jroper** [comment]
Hi @retronym,

That linked PR has nothing to do with it, it's on the master branch, and the community build of the Play SBT plugin appears to be building against the 2.3.x branch:

https://github.com/scala/community-builds/blob/master/common-2.11.x.conf#L718

It seems that the Play SBT plugin broke on April 2, it passed on April 1:

https://jenkins-dbuild.typesafe.com:8499/view/Shared/job/Community-2.11.x/505/console
https://jenkins-dbuild.typesafe.com:8499/view/Shared/job/Community-2.11.x/506/console

We had no changes on the 2.3.x branch between April 1 and April 2, the closest was a documentation change with no relation to the SBT plugin on March 31, and then no other changes until April 5:

https://github.com/playframework/playframework/commits/2.3.x

Exactly what is Play building against here?  Is it building against the master of sbteclipse?  If that's the case, here's the commit that broke it:

https://github.com/typesafehub/sbteclipse/commit/280f2107d1eccb4de0ec2f65599dc38970f70e5c

We have no intention of fixing this in the 2.3.x branch, sbteclipse is undergoing major changes at the moment which are being done in sync with changes to Play, we can't switch to a newer version of sbteclipse in 2.3.x without backporting all the changes in Play back to 2.3.x.  I don't know why the community build is building against the 2.3.x branch, but that's probably the problem here.

**Comment by retronym** [comment]
We can just fix on a known-compatible tag of sbt-eclipse.

**Comment by retronym** [comment]
Should I try v3.0.0 of sbt-eclipse?

I'll open a separate ticket to move the community build from 2.3.x to 2.4.x. Usually we try to focus on a widely used version, rather than a bleeding edge version, so it might not be appropriate to switch immediately.

**Comment by jroper** [comment]
Fair enough.  v3.0.0 should be fine.  Perhaps there should be a 3.x branch of sbteclipse.
